# Main executable C sources, grouped by compiler and small-data limit.
# Keep the order: these lists also determine the object order at link time.
# INCLUDE_ASM functions are pulled in by their C files and need no entry here.

SRCS_G0 := \
	src/psyq/libapi/C114.c \
	src/psyq/libapi/A81.c \
	src/psyq/libc2/bcopy.c \
	src/psyq/libc2/bzero.c \
	src/psyq/libc2/memcpy.c \
	src/psyq/libc2/memset.c \
	src/psyq/libc2/rand.c \
	src/psyq/libc2/strcat.c \
	src/psyq/libc2/strcmp.c \
	src/psyq/libc2/strcpy.c \
	src/psyq/libc2/strlen.c \
	src/psyq/libc2/strncmp.c \
	src/psyq/libc2/strncpy.c \
	src/psyq/libc2/exit.c \
	src/psyq/libcard/C171.c \
	src/psyq/libcard/C172.c \
	src/psyq/libcard/A78.c \
	src/psyq/libcard/A79.c \
	src/psyq/libcard/A80.c \
	src/psyq/libcard/A93.c \
	src/psyq/libcard/CARD.c \
	src/psyq/libcard/INIT.c \
	src/psyq/libapi/PAD.c \
	src/psyq/libapi/A18.c \
	src/psyq/libapi/A19.c \
	src/psyq/libapi/A20.c \
	src/psyq/libapi/A21.c \
	src/psyq/libapi/L02.c \
	src/psyq/libapi/L03.c \
	src/psyq/libapi/PATCH.c \
	src/psyq/libapi/C68.c \
	src/psyq/libapi/CHCLRPAD.c \
	src/psyq/libcard/A74.c \
	src/psyq/libcard/A75.c \
	src/psyq/libcard/A76.c \
	src/psyq/libcard/PATCH.c \
	src/psyq/libcard/END.c \
	src/psyq/libcard/FORMAT.c \
	src/psyq/libcard/A92.c \
	src/psyq/libpress/PRESS.c \
	src/psyq/libc2/PRINTF.c \
	src/psyq/libc2/PRNT.c \
	src/psyq/libc2/CTYPE.c \
	src/psyq/libc2/MEMCHR.c \
	src/psyq/libc2/PUTCHAR.c \
	src/psyq/libpress/VLC_C.c \
	src/psyq/libpress/BUILD.c \
	src/psyq/libgpu/SYS.c \
	src/psyq/libapi/C73.c \
	src/psyq/libgpu/BREAK.c \
	src/psyq/libgpu/EXT.c \
	src/psyq/libgpu/P17.c \
	src/psyq/libgpu/P18.c \
	src/psyq/libgte/GEO_00.c \
	src/psyq/libgte/GEO_01.c \
	src/psyq/libgte/COR_02.c \
	src/psyq/libgte/COR_01.c \
	src/psyq/libgte/COR_03.c \
	src/psyq/libgte/MSC00.c \
	src/psyq/libgte/MSC01.c \
	src/psyq/libgte/MSC02.c \
	src/psyq/libgte/MTX_003.c \
	src/psyq/libgte/MTX_004.c \
	src/psyq/libgte/MTX_006.c \
	src/psyq/libgte/MTX_07.c \
	src/psyq/libgte/MTX_08.c \
	src/psyq/libgte/MTX_09.c \
	src/psyq/libgte/MTX_12.c \
	src/psyq/libgte/REG12.c \
	src/psyq/libgte/REG13.c \
	src/psyq/libgte/SMP_05.c \
	src/psyq/libgte/FGO_01.c \
	src/psyq/libgte/FGO_04.c \
	src/psyq/libgte/FGO_05.c \
	src/psyq/libgte/FGO_06.c \
	src/psyq/libgte/RMAT_01.c \
	src/psyq/libgte/RATAN.c \
	src/psyq/libgte/PATCHGTE.c \
	src/psyq/libcd/EVENT.c \
	src/psyq/libapi/A07.c \
	src/psyq/libcd/SYS.c \
	src/psyq/libcd/BIOS.c \
	src/psyq/libc2/PUTS.c \
	src/psyq/libcd/TYPE.c \
	src/psyq/libcd/S_002.c \
	src/psyq/libetc/VSYNC.c \
	src/psyq/libapi/L10.c \
	src/psyq/libetc/INTR.c \
	src/psyq/libapi/A23.c \
	src/psyq/libapi/A24.c \
	src/psyq/libapi/A25.c \
	src/psyq/libc2/SETJMP.c \
	src/psyq/libetc/INTR_VB.c \
	src/psyq/libetc/INTR_DMA.c \
	src/psyq/libetc/VMODE.c \
	src/psyq/libspu/S_I.c \
	src/psyq/libspu/S_INI.c \
	src/psyq/libspu/SPU.c \
	src/psyq/libspu/S_DCB.c \
	src/psyq/libspu/S_SI.c \
	src/psyq/libspu/S_SIA.c \
	src/psyq/libspu/S_STSA.c \
	src/psyq/libspu/S_SRA.c \
	src/psyq/libapi/A13.c \
	src/psyq/libapi/A32.c \
	src/psyq/libapi/COUNTER.c \
	src/psyq/libspu/S_Q.c \
	src/psyq/libspu/S_M_INIT.c \
	src/psyq/libspu/S_SR.c \
	src/psyq/libspu/S_M_UTIL.c \
	src/psyq/libspu/S_SIC.c \
	src/psyq/libspu/S_SNC.c \
	src/psyq/libspu/S_GVEX.c \
	src/psyq/libspu/S_SRMD.c \
	src/psyq/libspu/S_CB.c \
	src/psyq/libspu/S_R.c \
	src/psyq/libspu/S_W.c \
	src/psyq/libspu/S_STM.c \
	src/psyq/libspu/S_STC.c \
	src/psyq/libcard/C112.c \
	src/psyq/libapi/C159.c \
	src/psyq/libapi/A08.c \
	src/psyq/libapi/A09.c \
	src/psyq/libapi/A11.c \
	src/psyq/libapi/A12.c \
	src/psyq/libapi/A36.c \
	src/psyq/libapi/A37.c \
	src/psyq/libapi/A50.c \
	src/psyq/libapi/A52.c \
	src/psyq/libapi/A53.c \
	src/psyq/libapi/A54.c \
	src/psyq/libapi/A67.c \
	src/psyq/libapi/A68.c \
	src/psyq/libapi/A69.c \
	src/psyq/libapi/A91.c \
	src/psyq/libapi/SC2B.c \
	src/psyq/libapi/FIRST.c \
	src/psyq/libapi/A66.c \
	src/psyq/libspu/S_SRMT.c \
	src/psyq/libspu/S_CRWA.c \
	src/psyq/libapi/A10.c \
	src/psyq/libspu/S_GRMT.c \
	src/psyq/libsn/SNMAIN.c \
	src/psyq/libapi/C57.c \
	src/psyq/libpad/PADENTRY.c \
	src/psyq/libpad/PADMAIN.c \
	src/psyq/libpad/PADCMD.c \
	src/psyq/libpad/PADIF.c \
	src/psyq/libpad/PADPORTD.c \
	src/psyq/libpad/PADSEQD.c \
	src/psyq/libmcx/TMP_MCX.c \
	src/screen_transition.c \
	src/game_audio.c \
	src/akao_cmd.c \
	src/field_runtime.c \
	src/main.c

SRCS_G4 := \
	src/cdrom.c \
	src/cdrom_decompress.c \
	src/overlay_memory.c \
	src/akao_sequencer.c \
	src/akao_driver.c \
	src/akao_driver_init_state.c \
	src/akao_driver_boot.c \
	src/controller.c \
	src/akao_voice.c \
	src/akao_control.c \
	src/akao_xa_stream.c

SRCS_GCC_260_G0 := \
	src/field_runtime_text.c \
	src/field_runtime_glyph.c \
	src/card_callbacks.c
