# ============================================================================
#  Overlay System
# ============================================================================
#
# Overlays are small executables loaded on top of the main SLUS at runtime.
# Each overlay follows the same directory convention:
#
#   src/overlays/<name>/         — decompiled C source files
#   asm/overlays/<name>/         — splat-generated disassembly
#   linker/overlays/<name>/      — linker scripts from splat
#   build/overlays/<name>/       — compiled objects and output ELF
#   assets/                      — gitignored binary data generated by splat
#
# ── How to add a new overlay ─────────────────────────────────────────────────
#
#   1. Create config/overlays/<NAME>.BIN.yaml.
#   2. Run: splat split config/overlays/<NAME>.BIN.yaml
#   3. In mk/overlay-registry.mk, register the overlay and explicitly route
#      every direct C source to one toolchain configuration.
#
# ─────────────────────────────────────────────────────────────────────────────


# ── Overlay rule template ────────────────────────────────────────────────────
#
# This define block is a "macro" that generates all Make rules for one overlay.
# It's called once per entry in OVERLAYS via $(eval $(call ...)) at the bottom.
#
# Inside the template:
#   $(1)  = overlay name (e.g. "checkps")
#   $$    = escaped $ (needed because eval expands variables twice)

# Return every word that occurs more than once in a list.
duplicate-words = $(sort $(foreach item,$(1),$(if $(word 2,$(filter $(item),$(1))),$(item))))

# Validate the registry itself before generating any overlay rules.
DUPLICATE_OVERLAYS := $(call duplicate-words,$(OVERLAYS))
OVERLAY_REQUIRED_DIRS := $(foreach name,$(OVERLAYS),\
	src/overlays/$(name) asm/overlays/$(name) linker/overlays/$(name))
MISSING_OVERLAY_DIRS := $(filter-out $(wildcard $(OVERLAY_REQUIRED_DIRS)),$(OVERLAY_REQUIRED_DIRS))

ifneq ($(DUPLICATE_OVERLAYS),)
$(error Overlays registered more than once: $(DUPLICATE_OVERLAYS))
endif
ifneq ($(MISSING_OVERLAY_DIRS),)
$(error Registered overlay directories not found: $(MISSING_OVERLAY_DIRS))
endif

define overlay-rules

# ── Derived paths for overlay '$(1)' ──
$(1)_SRC_DIR   := src/overlays/$(1)
$(1)_ASM_DIR   := asm/overlays/$(1)
$(1)_LINK_DIR  := linker/overlays/$(1)
$(1)_BUILD_DIR := build/overlays/$(1)
$(1)_TARGET    := $(STAGING)/$$($(1)_BUILD_DIR)/$(1).elf
$(1)_LINKER_SCRIPTS := \
	$(STAGING)/$$($(1)_LINK_DIR)/$(1).ld \
	$(STAGING)/$$($(1)_LINK_DIR)/undefined_funcs_auto.txt \
	$(STAGING)/$$($(1)_LINK_DIR)/undefined_syms_auto.txt

# ── Discover and validate source routing ──
$(1)_C_SRCS := $$(wildcard $$($(1)_SRC_DIR)/*.c)
$(1)_GCC_272_CDK_G0_SRCS := $$(overlay_$(1)_gcc_272_cdk_g0_srcs)
$(1)_GCC_272_GNU_G0_SRCS := $$(overlay_$(1)_gcc_272_gnu_g0_srcs)
$(1)_GCC_280_G0_SRCS := $$(overlay_$(1)_gcc_280_g0_srcs)
$(1)_GCC_280_G4_SRCS := $$(overlay_$(1)_gcc_280_g4_srcs)
$(1)_GCC_280_G4_NOEXPAND_SRCS := $$(overlay_$(1)_gcc_280_g4_noexpand_srcs)
$(1)_ROUTED_SRCS := $$($(1)_GCC_272_CDK_G0_SRCS) $$($(1)_GCC_272_GNU_G0_SRCS) $$($(1)_GCC_280_G0_SRCS) $$($(1)_GCC_280_G4_SRCS) $$($(1)_GCC_280_G4_NOEXPAND_SRCS)
$(1)_UNROUTED_SRCS := $$(filter-out $$($(1)_ROUTED_SRCS),$$($(1)_C_SRCS))
$(1)_UNKNOWN_ROUTED_SRCS := $$(filter-out $$($(1)_C_SRCS),$$($(1)_ROUTED_SRCS))
$(1)_DUPLICATE_ROUTED_SRCS := $$(call duplicate-words,$$($(1)_ROUTED_SRCS))
$$(if $$($(1)_UNROUTED_SRCS),$$(error Overlay $(1) has unrouted source(s): $$($(1)_UNROUTED_SRCS)))
$$(if $$($(1)_UNKNOWN_ROUTED_SRCS),$$(error Overlay $(1) routes unknown source(s): $$($(1)_UNKNOWN_ROUTED_SRCS)))
$$(if $$($(1)_DUPLICATE_ROUTED_SRCS),$$(error Overlay $(1) routes source(s) more than once: $$($(1)_DUPLICATE_ROUTED_SRCS)))

$(1)_GCC_280_G4_ALL_SRCS := $$($(1)_GCC_280_G4_SRCS) $$($(1)_GCC_280_G4_NOEXPAND_SRCS)

# ── Derive object paths ──
$(1)_GCC_280_G0_OBJS := $$(patsubst $$($(1)_SRC_DIR)/%.c,$(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o,$$($(1)_GCC_280_G0_SRCS))
$(1)_GCC_280_G4_OBJS := $$(patsubst $$($(1)_SRC_DIR)/%.c,$(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o,$$($(1)_GCC_280_G4_ALL_SRCS))
$(1)_GCC_280_G4_NOEXPAND_OBJS := $$(patsubst $$($(1)_SRC_DIR)/%.c,$(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o,$$($(1)_GCC_280_G4_NOEXPAND_SRCS))
$(1)_GCC_272_GNU_G0_OBJS := $$(patsubst $$($(1)_SRC_DIR)/%.c,$(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o,$$($(1)_GCC_272_GNU_G0_SRCS))
$(1)_GCC_272_CDK_G0_OBJS := $$(patsubst $$($(1)_SRC_DIR)/%.c,$(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o,$$($(1)_GCC_272_CDK_G0_SRCS))
# Clear the div-expansion flag for the no-expand subset (target-specific var).
$$($(1)_GCC_280_G4_NOEXPAND_OBJS): MASPSX_DIV_FLAG_G4 :=
$(1)_C_OBJS := $$($(1)_GCC_272_CDK_G0_OBJS) $$($(1)_GCC_280_G0_OBJS) $$($(1)_GCC_272_GNU_G0_OBJS) $$($(1)_GCC_280_G4_OBJS)

# ── Optional standalone binary object ──
# Use asset_src only when the linker script expects assets/<name>.o. This is
# separate from splat databin assets included by generated assembly below.
$(1)_ASSET_SRC := $$(overlay_$(1)_asset_src)
$(1)_ASSET_OBJ := $(STAGING)/$$($(1)_BUILD_DIR)/assets/$(1).o

# ── Splat-generated data assembly ──
# These files may use .incbin to include gitignored data from assets/.
# The splat-generated linker script pulls these .o files in directly by path
# (e.g. build/overlays/<name>/asm/overlays/<name>/data/rodata.rodata.o), so
# they must be assembled to that exact location even though they're excluded
# from the objdiff target-object set below.
$(1)_DATA_ASM  := $$(wildcard $$($(1)_ASM_DIR)/data/*.s)
$(1)_DATA_OBJS := $$(patsubst $$($(1)_ASM_DIR)/%.s,$(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_ASM_DIR)/%.o,$$($(1)_DATA_ASM))

$$($(1)_DATA_OBJS): $(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_ASM_DIR)/%.o: $$($(1)_ASM_DIR)/%.s $(COPY_SENTINEL)
	@mkdir -p $$(@D)
	cd $(STAGING) && cat $$($(1)_ASM_DIR)/$$*.s | \
		$(MASPSX) $(MASPSX_PP_FLAGS) | \
		$(MASPSX_AS) $(INCLUDE_FLAGS) $(MASPSX_FLAGS_272_CDK) -o $$($(1)_BUILD_DIR)/$$($(1)_ASM_DIR)/$$*.o

# Rule: compile matched C files with GCC 2.7.2 CDK G0 + maspsx
$$($(1)_GCC_272_CDK_G0_OBJS): $(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o: $$($(1)_SRC_DIR)/%.c $(COPY_SENTINEL)
	@mkdir -p $$(@D)
	cd $(STAGING) && $(CC_272_CDK) $(CFLAGS_272_CDK_G0) $(INCLUDE_FLAGS) -c $$($(1)_SRC_DIR)/$$*.c -S -o - | \
		$(MASPSX_AS) $(INCLUDE_FLAGS) $(MASPSX_FLAGS_272_CDK) -o $$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/$$*.o

# Rule: compile non-matching C files with GCC 2.8.0 G0 + maspsx.
$$($(1)_GCC_280_G0_OBJS): $(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o: $$($(1)_SRC_DIR)/%.c $(COPY_SENTINEL)
	@mkdir -p $$(@D)
	cd $(STAGING) && $(CC) $(CFLAGS_G0) $(INCLUDE_FLAGS) -c $$($(1)_SRC_DIR)/$$*.c -S -o - | \
		$(MASPSX_AS) $(INCLUDE_FLAGS) $(MASPSX_FLAGS) -o $$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/$$*.o

# Rule: compile C files with GCC 2.8.0 G4 + maspsx.
$$($(1)_GCC_280_G4_OBJS): $(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o: $$($(1)_SRC_DIR)/%.c $(COPY_SENTINEL)
	@mkdir -p $$(@D)
	cd $(STAGING) && $(CC) $(CFLAGS_G4) $(INCLUDE_FLAGS) -c $$($(1)_SRC_DIR)/$$*.c -S -o - | \
		$(MASPSX_AS) $(INCLUDE_FLAGS) $$(MASPSX_FLAGS_G4) -o $$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/$$*.o

# Rule: compile C files with GCC 2.7.2 GNU G0 + its own assembler.
$$($(1)_GCC_272_GNU_G0_OBJS): $(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/%.o: $$($(1)_SRC_DIR)/%.c $(COPY_SENTINEL)
	@mkdir -p $$(@D)
	cd $(STAGING) && $(CC_272_GNU) $(CFLAGS_272_GNU_G0) $(INCLUDE_FLAGS) -S $$($(1)_SRC_DIR)/$$*.c -o - | \
		$(AS_272_GNU) $(ASFLAGS_272_GNU) $(INCLUDE_FLAGS) -o $$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/$$*.o

# Rule: convert binary asset → linkable .o  (only if asset is defined)
ifneq ($$($(1)_ASSET_SRC),)
$$($(1)_ASSET_OBJ): $(STAGING)/$$($(1)_ASSET_SRC)
	@mkdir -p $$(@D)
	cd $(STAGING) && $(OBJCOPY) -I binary -O elf32-tradlittlemips -B mips \
		$$($(1)_ASSET_SRC) $$($(1)_BUILD_DIR)/assets/$(1).o
endif

# Rule: link the overlay ELF
# Dependencies include the asset object only if the overlay has an asset.
$$($(1)_TARGET): $(COPY_SENTINEL) $$($(1)_C_OBJS) $$($(1)_DATA_OBJS) $$(if $$($(1)_ASSET_SRC),$$($(1)_ASSET_OBJ)) $$($(1)_LINKER_SCRIPTS)
	@mkdir -p $$(@D)
	cd $(STAGING) && $(LD) -o $$($(1)_BUILD_DIR)/$(1).elf \
		-T $$($(1)_LINK_DIR)/$(1).ld \
		-T $$($(1)_LINK_DIR)/undefined_funcs_auto.txt \
		-T $$($(1)_LINK_DIR)/undefined_syms_auto.txt \
		$$(patsubst $(STAGING)/%,%,$$($(1)_C_OBJS)) \
		-Map $$($(1)_BUILD_DIR)/$(1).map
	@echo "Linked overlay: $(1)"

# ── Objdiff rules for this overlay ──
$(1)_ALL_ASM    := $$(call rwildcard,$$($(1)_ASM_DIR),*.s)
$(1)_TGT_ASM   := $$(filter-out $$($(1)_ASM_DIR)/nonmatchings/% $$($(1)_ASM_DIR)/data/%,$$($(1)_ALL_ASM))
$(1)_TGT_OBJS  := $$(patsubst $$($(1)_ASM_DIR)/%.s,$(STAGING)/$$($(1)_BUILD_DIR)/target/%.o,$$($(1)_TGT_ASM))

$$($(1)_TGT_OBJS): $(STAGING)/$$($(1)_BUILD_DIR)/target/%.o: $$($(1)_ASM_DIR)/%.s $(COPY_SENTINEL)
	@mkdir -p $$(@D)
	cd $(STAGING) && cat $$($(1)_ASM_DIR)/$$*.s | \
		$(MASPSX) $(MASPSX_PP_FLAGS) | \
		$(MASPSX_AS) $(INCLUDE_FLAGS) $(MASPSX_FLAGS_272_CDK) -o $$($(1)_BUILD_DIR)/target/$$*.o

# ── Phony convenience targets ──
.PHONY: $(1) $(1)-target-objects $(1)-base-objects $(1)-objdiff

$(1): $$($(1)_TARGET)
	@mkdir -p $$($(1)_BUILD_DIR)
	@cp -a "$(STAGING)/$$($(1)_BUILD_DIR)/." "$$($(1)_BUILD_DIR)/"
	@echo "Overlay $(1) build complete."

$(1)-target-objects: $(COPY_SENTINEL) $$($(1)_TGT_OBJS)
	@mkdir -p $$($(1)_BUILD_DIR)/target
	@if [ -n "$$(strip $$($(1)_TGT_OBJS))" ]; then \
		cp -a "$(STAGING)/$$($(1)_BUILD_DIR)/target/." "$$($(1)_BUILD_DIR)/target/"; \
	fi

$(1)-base-objects: $(COPY_SENTINEL) $$($(1)_C_OBJS)
	@mkdir -p $$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)
	@cp -a "$(STAGING)/$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/." \
		"$$($(1)_BUILD_DIR)/$$($(1)_SRC_DIR)/"

$(1)-objdiff: $(1)-target-objects $(1)-base-objects

endef

# ── Instantiate rules for every registered overlay ──
# This line loops over OVERLAYS and calls the template above for each one.
# $(eval) tells Make to treat the output as real Makefile syntax.
$(foreach ov,$(OVERLAYS),$(eval $(call overlay-rules,$(ov))))

# ── Aggregate overlay targets ──
.PHONY: overlays everything

overlays: $(OVERLAYS)
	@echo "All overlays built."

everything: all overlays
	@echo "Full build complete."
