name: CLOAD.BIN
sha1: 9aa31d6f62ee68bff73bbe0e8b4416e34bb20e58
options:
  base_path: ../../
  basename: CLOAD.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/CLOAD.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/cload.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/cload
  src_path: src/overlays/cload
  build_path: build/overlays/cload

  ld_script_path: linker/overlays/cload/cload.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/cload/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/cload/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/overlays/cload_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: cload
    type: decompress_overlay
    start: 0x1
    vram: 0x80140000
    subsegments:
      - [0x1, rodata, rodata]
      - [0xC5, c, cload]     # gcc272_cdk
      - [0x5765, c, unk1]
      - [0x5E9D, data, data]
  - [0x2B259]