name: FIELD.BIN
sha1: 5b0325f90d55daef8321606d9a439238b0a5518d
options:
  base_path: ../../
  basename: FIELD.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/FIELD.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/field.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/field
  src_path: src/overlays/field
  build_path: build/overlays/field

  ld_script_path: linker/overlays/field/field.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/field/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/field/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/symbols/shared_symbol_addrs.txt
    - config/symbols/field_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: field
    type: decompress_overlay
    start: 0x1
    vram: 0x8004FC70
    subsegments:
      - [0x1, rodata, rodata]
      - [0x22B9, c, field1]
      - [0x29B9, c, field2]
      - [0x3C11, c, field3]
      - [0x400D, c, unk1]
      - [0x1861D, c, field4]
      - [0x19F15, c, unk2]
      - [0x7C2D5, data, data]
  - [0xD4368]