name: FIELD.BIN
sha1: 5b0325f90d55daef8321606d9a439238b0a5518d
options:
  base_path: ../../
  basename: FIELD.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/FIELD.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/field.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/field
  src_path: src/overlays/field
  build_path: build/overlays/field

  ld_script_path: linker/overlays/field/field.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/field/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/field/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/symbols/shared_symbol_addrs.txt
    - config/symbols/field_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: field
    type: decompress_overlay
    start: 0x1
    vram: 0x8004FC70
    subsegments:
      - [0x1, rodata, rodata]
      - [0x5, .rodata, field3]
      - [0x65, .rodata, unk1]
      - [0x115, .rodata, unk1_e]
      - [0x129, .rodata, unk1_c]
      - [0x26D, .rodata, unk1_c_b]
      - [0x285, .rodata, unk2]
      - [0x22B9, c, field1]       # gcc280_g4
      - [0x29B9, c, field2]       # gcc280_g4
      - [0x3C11, c, field3]       # CDK (default)
      - [0x4B0D, c, field8]      # gcc280_g4
      - [0x4C95, c, unk1]
      - [0x9555, c, func_800591C4] # gcc280_g4
      - [0x9625, c, func_80059294] # gcc280_g4
      - [0x9645, c, unk1_e]
      - [0xAEDD, c, func_8005ab4c] # gcc280_g4
      - [0xAF11, c, unk1_e_tail]
      - [0xB57D, c, field6] # gcc280_g4
      - [0xBA3D, c, field7] # gcc280_g4
      - [0xDE0D, c, unk1_c]
      - [0x1462D, c, func_8006429c] # gcc280_g4
      - [0x14665, c, unk1_c_b]
      - [0x17839, c, func_800674a8] # gcc280_g4
      - [0x17869, c, unk1_c_tail]
      - [0x17929, c, func_80067598] # gcc280_g4
      - [0x17959, c, unk1_c_tail2]
      - [0x17F1D, c, func_80067b8c] # gcc280_g4
      - [0x17F4D, c, unk1_c_tail3]
      - [0x18245, c, field5] # gcc280_g4
      - [0x18341, c, unk1_f]
      - [0x18551, c, func_800681c0] # gcc272_cdk
      - [0x18575, c, unk1_g]
      - [0x1861D, c, field4]      # CDK (default)
      - [0x1AC1D, c, unk2]
      - [0x7C2D5, data, data]
  - [0xD4368]