name: GNAME.BIN
sha1: e428114bd699f557d3508a4f26a8e3c2c495db29
options:
  base_path: ../../
  basename: GNAME.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/GNAME.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/gname.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/gname
  src_path: src/overlays/gname
  build_path: build/overlays/gname

  ld_script_path: linker/overlays/gname/gname.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/gname/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/gname/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/overlays/gname_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: gname
    type: decompress_overlay
    start: 0x1
    vram: 0x80140000
    subsegments:
      - [0x1, rodata, rodata]
      - [0x3E1, c, gname]
      - [0x2765, c, unk1]
      - [0x2C99, data, data]
  - [0xF8D9]