name: GOLEM.BIN
sha1: daf8ab21241b9613ed0ada1fa540dd254fe27306
options:
  base_path: ../../
  basename: GOLEM.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/GOLEM.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/golem.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/golem
  src_path: src/overlays/golem
  build_path: build/overlays/golem

  ld_script_path: linker/overlays/golem/golem.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/golem/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/golem/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/overlays/golem_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: golem
    type: decompress_overlay
    start: 0x1
    vram: 0x80140000
    subsegments:
      - [0x1, rodata, rodata]
      - [0x25, c, golem]
      - [0x1AD1, c, unk1]
      - [0x287D, data, data]
  - [0xC28D]