name: GOSUB.BIN
sha1: 1361a14f2d461fd99c2e9d5d4f5e70b7704bb098
options:
  base_path: ../../
  basename: GOSUB.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/GOSUB.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/gosub.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/gosub
  src_path: src/overlays/gosub
  build_path: build/overlays/gosub

  ld_script_path: linker/overlays/gosub/gosub.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/gosub/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/gosub/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/overlays/gosub_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: gosub
    type: decompress_overlay
    start: 0x1
    vram: 0x80140000 #This might be incorrect fix it later when we know the correct VRAM address
    subsegments:
      - [0x1, rodata, rodata]
      - [0x81, c, gosub]       # CDK (default)
      - [0x13C1, c, unk1]
      - [0x28D9, data, data]
  - [0x34A5D]