name: MOVIE.BIN
sha1: 4ede2a498e06efdf712414b052bb21fe0d198298
options:
  base_path: ../../
  basename: MOVIE.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/MOVIE.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/movie.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/movie
  src_path: src/overlays/movie
  build_path: build/overlays/movie

  ld_script_path: linker/overlays/movie/movie.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/movie/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/movie/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/overlays/movie_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: movie
    type: decompress_overlay
    start: 0x1
    vram: 0x80140000
    subsegments:
      - [0x1, rodata, rodata]
      - [0x19, c, movie1]
      - [0x18B1, c, unk1]
  - [0x1914]