name: SHOP.BIN
sha1: 09645449948177200d87cb9350a87df165e34453
options:
  base_path: ../../
  basename: SHOP.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/SHOP.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/shop.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/shop
  src_path: src/overlays/shop
  build_path: build/overlays/shop

  ld_script_path: linker/overlays/shop/shop.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/shop/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/shop/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/overlays/shop_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: shop
    type: decompress_overlay
    start: 0x1
    vram: 0x80140000 #This is incorrect fix it later when we know the correct VRAM address
    subsegments:
      - [0x1, rodata, rodata]
      - [0x5, c, unk1]
      - [0x2D05, data, data]
  - [0x30C7]