name: TITLE.BIN
sha1: 4df07f0d2b3a850751f74d91c5ca96a1fdbb998e
options:
  base_path: ../../
  basename: TITLE.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/TITLE.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/title.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/title
  src_path: src/overlays/title
  build_path: build/overlays/title

  ld_script_path: linker/overlays/title/title.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/title/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/title/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/overlays/title_symbol_addrs.txt

  reloc_addrs_path:
    - config/overlays/title_reloc_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: title
    type: decompress_overlay
    start: 0x1
    vram: 0x8004FC70
    subsegments:
      - [0x1, rodata, rodata]
      - [0x5, c, title1]
      - [0x1275, c, unk1]
      - [0x2679, data, data]
  - [0xB2A5D]