name: WSEL.BIN
sha1: 3f5b45b81cfd83dbad6c2853e4befd769d9a0468
options:
  base_path: ../../
  basename: WSEL.BIN
  platform: psx
  compiler: PSYQ
  target_path: disc/BIN/WSEL.BIN
  extensions_path: tools/splat_ext
  asset_path: assets
  elf_path: build/overlays/wsel.elf

  # Overlay-specific output paths (separate from SLUS)
  asm_path: asm/overlays/wsel
  src_path: src/overlays/wsel
  build_path: build/overlays/wsel

  ld_script_path: linker/overlays/wsel/wsel.ld
  ld_dependencies: True
  undefined_funcs_auto_path: linker/overlays/wsel/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/overlays/wsel/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/overlays/wsel_symbol_addrs.txt

  find_file_boundaries: False
  make_full_disasm_for_code: True
  use_legacy_include_asm: False
  o_as_suffix: True
  subalign: 2

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  string_encoding: ASCII
  data_string_encoding: ASCII

segments:
  - name: wsel
    type: decompress_overlay
    start: 0x1
    vram: 0x8004FC70
    subsegments:
      - [0x1, rodata, rodata]
      - [0xB5, c, unk1]
  - [0x459E1]