"""Write a data region as C.

There are two outputs:

- For the PS1 build (the default), GCC 2.8 must reproduce the original bytes
  and relocations exactly (checked by `make DATA_AS_C=1 verify-bins`). Runs of
  symbols GCC would misalign become packed clusters, and PS1 padding bytes are
  written out.
- For a host build (`host=True`), the same values are written for a compiler
  with wider pointers: every symbol is its own object, the host compiler does
  its own padding, and each integer keeps its declared C type (a `long` stays
  a `long`), so the data lays out the way host-compiled game code expects.
  hostcheck.py proves the values survive.

In both, every stored pointer is a real C pointer initializer, not a number.

Types are written structurally (D2C_S000, D2C_U001, ...) instead of reusing the
decomp's names, because the decomp's types are often private to one .c file.
Two types with the same layout share one generated name.
"""
from __future__ import annotations

import re
import struct

from declarations import (TypeKind, choose, is_integer, is_signed, is_union, layout_key, points_to_function,
                          record_members)
from symbols import RAM_END, RAM_START

HEADER = ("/* Generated by tools/verification/data2c from the user's own game data. Do not commit. */\n"
          "typedef signed char s8;\ntypedef unsigned char u8;\ntypedef short s16;\ntypedef unsigned short u16;\n"
          "typedef int s32;\ntypedef unsigned int u32;\ntypedef long long s64;\ntypedef unsigned long long u64;\n\n")


def wrap(items) -> str:
    """A brace initializer, broken into lines of about 110 characters."""
    if sum(len(i) for i in items) < 100:
        return "{ " + ", ".join(items) + " }"
    lines = []
    cur = ""
    for it in items:
        if len(cur) + len(it) > 110:
            lines.append(cur.rstrip())
            cur = ""
        cur += it + ", "
    lines.append(cur.rstrip())
    return "{\n    " + "\n    ".join(lines) + "\n}"


def number(v: int) -> str:
    return str(v) if -10 < v < 10 else (f"{v:#x}" if v >= 0 else f"-{-v:#x}")


def byte_list(data: bytes) -> list[str]:
    return [f"{b:#04x}" for b in data]


# ----------------------------------------------------------------------------- types

# Host integer spelling by declared kind, so the host lays each one out as the
# game's own headers do.
HOST_INTEGERS = {
    TypeKind.CHAR_S: "s8", TypeKind.SCHAR: "s8", TypeKind.CHAR_U: "u8", TypeKind.UCHAR: "u8",
    TypeKind.SHORT: "s16", TypeKind.USHORT: "u16", TypeKind.INT: "s32", TypeKind.UINT: "u32",
    TypeKind.LONG: "long", TypeKind.ULONG: "unsigned long",
    TypeKind.LONGLONG: "s64", TypeKind.ULONGLONG: "u64", TypeKind.BOOL: "u8",
}


def host_key(t) -> str:
    """Like layout_key, but integers keep their declared kind: on a host a
    `long` and an `int` of the same PS1 size lay out differently."""
    t = t.get_canonical()
    k = t.kind
    if is_integer(t):
        return HOST_INTEGERS.get(k, "s32")
    if k in (TypeKind.CONSTANTARRAY, TypeKind.INCOMPLETEARRAY):
        n = t.element_count if k == TypeKind.CONSTANTARRAY else ""
        return f"[{n}]{host_key(t.element_type)}"
    if k == TypeKind.RECORD:
        fields = [host_key(f.type) + (f":{f.get_bitfield_width()}" if f.is_bitfield() else "") for f in t.get_fields()]
        return ("U" if is_union(t) else "S") + "{" + ",".join(fields) + "}" + layout_key(t)
    return layout_key(t)


class TypeWriter:
    """C text for libclang types, with records written out structurally."""

    def __init__(self, host: bool = False):
        self.host = host
        self.names = {}            # layout key -> generated record name
        self.definitions = []      # record typedefs, each after the records it uses

    def declarator(self, t, name: str) -> str:
        """`type name` for a declaration of `name` with type `t`."""
        t = t.get_canonical()
        k = t.kind
        if is_integer(t):
            if self.host:
                return f"{HOST_INTEGERS.get(k, 's32')} {name}"
            return f"{self.integer(t)} {name}"
        if k == TypeKind.POINTER:
            # Every data pointer is void * and every code pointer void (*)(): only
            # the width matters for the layout, and initializers carry casts.
            return f"void (*{name})()" if points_to_function(t) else f"void *{name}"
        if k == TypeKind.CONSTANTARRAY:
            return self.declarator(t.element_type, f"{name}[{t.element_count}]")
        if k == TypeKind.INCOMPLETEARRAY:
            return self.declarator(t.element_type, f"{name}[]")
        if k == TypeKind.RECORD:
            return f"{self.record(t)} {name}"
        if k == TypeKind.FLOAT:
            return f"float {name}"
        raise ValueError(f"unsupported type {t.spelling} ({k})")

    @staticmethod
    def integer(t) -> str:
        signed = is_signed(t)
        return {1: "s8" if signed else "u8", 2: "s16" if signed else "u16",
                4: "s32" if signed else "u32", 8: "s64" if signed else "u64"}[t.get_size()]

    def record(self, t) -> str:
        key = host_key(t) if self.host else layout_key(t)
        if key in self.names:
            return self.names[key]
        name = f"D2C_{'U' if is_union(t) else 'S'}{len(self.names):03d}"
        self.names[key] = name      # before the members, so nested records number after it
        members = []
        for i, m in enumerate(record_members(t)):
            if m[0] == "pad":
                if not self.host:   # a host pads by its own rules
                    members.append(f"    u8 d2c_pad_{m[1]:02X}[{m[2]}];")
                continue
            f = m[1]
            decl = self.declarator(f.type, f.spelling or f"unnamed_{i}")
            if f.is_bitfield():
                decl += f" : {f.get_bitfield_width()}"
            members.append(f"    {decl};")
        # A record aligned below its widest member was declared packed.
        natural = max([f.type.get_canonical().get_align() for f in t.get_fields()] or [1])
        packed = " __attribute__((packed))" if t.get_align() < natural else ""
        kind = "union" if is_union(t) else "struct"
        self.definitions.append(f"typedef {kind}\n{{\n" + "\n".join(members) + f"\n}}{packed} {name};\n")
        return name


# ----------------------------------------------------------------------------- initializers

class InitWriter:
    """C initializers for a region's bytes, typed by a declaration."""

    def __init__(self, region, symbols, report, host: bool = False):
        self.region = region
        self.symbols = symbols
        self.report = report
        self.host = host
        self.externs = {}          # referenced name -> "func" | "data"
        self.pointer_words = set() # addresses written as symbolic pointers

    def pointer_to(self, name: str, offset: int, code_field: bool) -> str:
        """Initializer for a pointer to `name` + `offset`."""
        func = offset == 0 and self.symbols.is_function(name)
        self.externs.setdefault(name, "func" if func else "data")
        if func:
            self.report.count("pointer to function")
            return f"(void (*)()){name}" if code_field else f"(void *){name}"
        self.report.count("pointer to data")
        expr = f"(void *)((u8 *)&{name} + {offset:#x})" if offset else f"(void *)&{name}"
        return f"(void (*)()){expr}" if code_field else expr

    def pointer(self, addr: int, code_field: bool, where: str) -> str:
        """A pointer field. From an object, relocations say what it points to;
        a databin's value is looked up in the symbol table instead."""
        if addr in self.region.relocations:
            self.pointer_words.add(addr)
            return self.pointer_to(*self.region.relocations[addr], code_field)
        value = self.region.word(addr)
        if self.region.from_object and value:
            self.report.note("pointer field without a relocation", f"{where}: {value:#x}")
            return f"(void *){value:#x}"
        if value == 0:
            return "0"
        found = self.symbols.resolve(value)
        if found is None:
            self.report.note("raw address (no symbol)", f"{where}: {value:#x}")
            return f"(void *){value:#x}"
        self.pointer_words.add(addr)
        return self.pointer_to(*found, code_field)

    def value(self, t, addr: int, where: str, count: int | None = None) -> str:
        """Initializer for a value of type `t` stored at `addr`. `count` gives the
        length of an array declared without one."""
        t = t.get_canonical()
        k = t.kind
        if is_integer(t):
            return self.integer(t, addr, where)
        if k == TypeKind.POINTER:
            return self.pointer(addr, points_to_function(t), where)
        if k in (TypeKind.CONSTANTARRAY, TypeKind.INCOMPLETEARRAY):
            element = t.element_type.get_canonical()
            n = t.element_count if k == TypeKind.CONSTANTARRAY else count
            size = element.get_size()
            return wrap([self.value(element, addr + i * size, f"{where}[{i}]") for i in range(n)])
        if k == TypeKind.RECORD:
            return self.record(t, addr, where)
        if k == TypeKind.FLOAT:
            return repr(struct.unpack_from("<f", self.region.data, addr - self.region.start)[0]) + "f"
        raise ValueError(f"unsupported {t.spelling}")

    def integer(self, t, addr: int, where: str) -> str:
        size = t.get_size()
        if addr in self.region.relocations:
            # The declaration says integer, the data says address: keep the address.
            if size != 4:
                raise ValueError(f"relocation in a {size}-byte field at {where}")
            target, addend = self.region.relocations[addr]
            self.report.note("integer field holding an address", f"{where} -> {target}")
            return f"(u32){self.pointer_to(target, addend, False)}"
        v = self.region.word(addr, size, is_signed(t))
        if (not self.region.from_object and size == 4 and not is_signed(t)
                and RAM_START <= v < RAM_END and self.symbols.resolve(v, 0x100)):
            self.report.note("integer field holding an address", f"{where} = {v:#x}")
        return number(v)

    def record(self, t, addr: int, where: str) -> str:
        members = record_members(t)
        if is_union(t):
            self.report.count("union (widest member initialized)")
            members = members[:1]
            covered = members[0][1].type.get_canonical().get_size()
            if covered < t.get_size() and any(self.region.bytes_at(addr + covered, t.get_size() - covered)):
                self.report.note("union tail bytes lost", where)
        items = []
        for m in members:
            if m[0] == "pad" and self.host:
                if any(self.region.bytes_at(addr + m[1], m[2])):
                    self.report.note("nonzero padding dropped for the host", f"{where}+{m[1]:#x}")
                continue
            if m[0] == "pad":
                _, offset, size = m
                if any(addr + offset <= a < addr + offset + size for a in self.region.relocations):
                    raise ValueError(f"relocation in padding of {where}")
                chunk = self.region.bytes_at(addr + offset, size)
                if any(chunk):
                    self.report.note("nonzero padding kept as bytes", f"{where}+{offset:#x}")
                items.append("{ " + ", ".join(byte_list(chunk)) + " }")
                continue
            f = m[1]
            offset_bits = t.get_offset(f.spelling)
            if f.is_bitfield():
                # Little-endian bit numbering: read the bytes the field spans,
                # which also covers a field that crosses a word boundary.
                width = f.get_bitfield_width()
                first, last = offset_bits // 8, (offset_bits + width + 7) // 8
                bits = int.from_bytes(self.region.bytes_at(addr + first, last - first), "little")
                self.report.count("bitfield")
                items.append(str((bits >> (offset_bits % 8)) & ((1 << width) - 1)))
                continue
            items.append(self.value(f.type, addr + offset_bits // 8, f"{where}.{f.spelling}"))
        return "{ " + ", ".join(items) + " }"

    def untyped(self, name: str, addr: int, size: int):
        """Declarator and initializer for bytes with no usable type. Where a
        relocation falls they become 32-bit words, so the address survives."""
        inside = [a for a in self.region.relocations if addr <= a < addr + size]
        if not inside:
            return f"u8 {name}[{size}]", wrap(byte_list(self.region.bytes_at(addr, size)))
        if addr % 4 or size % 4 or any(a % 4 for a in inside):
            raise ValueError(f"relocation in unaligned bytes at {addr:#x}")
        if self.host:
            # An address does not fit a 32-bit word on the host: keep pointer-sized entries.
            items = []
            for a in range(addr, addr + size, 4):
                if a in self.region.relocations:
                    items.append(self.pointer_to(*self.region.relocations[a], False))
                else:
                    items.append(f"(void *){self.region.word(a):#x}")
            self.report.note("untyped words with addresses kept as pointers", name)
            return f"void *{name}[{size // 4}]", wrap(items)
        items = []
        for a in range(addr, addr + size, 4):
            if a in self.region.relocations:
                target, addend = self.region.relocations[a]
                items.append(f"(u32){self.pointer_to(target, addend, False)}")
                self.report.note("address in untyped data kept as a word", f"{name}+{a - addr:#x} -> {target}")
            else:
                items.append(f"{self.region.word(a):#x}")
        return f"u32 {name}[{size // 4}]", wrap(items)


# ----------------------------------------------------------------------------- the region

class RegionWriter:
    """Walk a region symbol by symbol and collect one definition per piece."""

    def __init__(self, region, symbols, declarations, report, host: bool = False):
        self.region = region
        self.symbols = symbols
        self.decls = declarations
        self.report = report
        self.host = host
        self.types = TypeWriter(host)
        self.inits = InitWriter(region, symbols, report, host)
        self.entries = []          # {"addr", "name", "decl", "init"} in address order
        self.aliases = []          # (name, target, offset) the C cannot define itself
        self.defined = set()
        self.chosen = {}           # symbol -> (declaration index, element count) for hostcheck.py

    def generate(self) -> str:
        starts = self.symbols.in_range(self.region.start, self.region.end)
        cursor = self.region.start
        for i, addr in enumerate(starts):
            end = starts[i + 1] if i + 1 < len(starts) else self.region.end
            if addr > cursor:
                self.gap(cursor, addr)
            cursor = self.symbol(addr, end - addr)
        if cursor < self.region.end:
            self.gap(cursor, self.region.end)
        return self.text()

    def add(self, addr: int, name: str, decl: str, init: str, align: int):
        self.entries.append({"addr": addr, "name": name, "decl": decl, "init": init, "align": align})

    def add_untyped(self, addr: int, name: str, size: int):
        # Untyped bytes are always an array (u8[] or u32[]), so word aligned.
        self.add(addr, name, *self.inits.untyped(name, addr, size), WORD)

    def gap(self, start: int, end: int):
        """Bytes between one symbol's type and the next symbol."""
        self.add_untyped(start, f"d2c_gap_{start:08X}", end - start)
        self.report.count("gap bytes before a symbol", end - start)

    def symbol(self, addr: int, extent: int) -> int:
        """Define the symbol at `addr`, which owns `extent` bytes. Returns the
        address where its definition ends."""
        names = self.symbols.names_at(addr)
        name = names[0]
        for alias in names[1:]:
            self.aliases.append((alias, name, 0))
        if len(names) > 1:
            self.report.note("aliases at one address", ", ".join(names))
        self.defined.add(name)

        candidates = self.decls.for_names(names)
        if not candidates:
            self.note_undeclared(name, addr, extent)
            self.add_untyped(addr, name, extent)
            return addr + extent

        t = choose(candidates, extent, self.report, name).get_canonical()
        position = next(i for i, (ct, _) in enumerate(candidates) if ct.get_canonical() == t)
        count = None
        if t.kind == TypeKind.INCOMPLETEARRAY:
            # `T name[]`: the symbol's extent says how many elements there are.
            element_size = t.element_type.get_canonical().get_size()
            count = extent // element_size
            if count * element_size != extent:
                self.report.note("incomplete array extent not a multiple of its element",
                                 f"{name}: {extent:#x}/{element_size:#x}")
            decl = self.types.declarator(t.element_type, f"{name}[{count}]")
            size = count * element_size
        else:
            decl = self.types.declarator(t, name)
            size = t.get_size()
        if size > extent:
            self.report.note("declared type larger than the symbol's extent", f"{name}: {size:#x} > {extent:#x}")
            self.add_untyped(addr, name, extent)
            return addr + extent
        try:
            init = self.inits.value(t, addr, name, count)
        except ValueError as ex:
            self.report.note("unsupported type", f"{name}: {ex}")
            self.add_untyped(addr, name, extent)
            return addr + extent
        self.add(addr, name, decl, init, gcc_alignment(t))
        self.chosen[name] = (position, count)
        self.report.count("typed symbols")
        self.report.count("alias needs a #define or code change", len(names) - 1)
        return addr + size

    def note_undeclared(self, name, addr, extent):
        chunk = self.region.bytes_at(addr, extent)
        words = sum(1 for o in range(0, len(chunk) - 3, 4)
                    if self.symbols.resolve(int.from_bytes(chunk[o:o + 4], "little"), 0x100) and (addr + o) % 4 == 0)
        self.report.note("symbol without a C declaration", f"{name} ({extent:#x} bytes, {words} address-like words)")

    # -- output

    def text(self) -> str:
        if self.host:
            forward = [f"extern {e['decl']};" for e in self.entries]
            body = [f"{e['decl']} = {e['init']};\n" for e in self.entries]
            externs = [f"extern void {n}();" if kind == "func" else f"extern u8 {n}[];"
                       for n, kind in sorted(self.inits.externs.items()) if n not in self.defined]
            return (HEADER + "\n".join(self.types.definitions) + "\n" + "\n".join(externs) + "\n\n"
                    + "\n".join(forward) + "\n\n" + "\n".join(body) + "\n" + host_alias_block(self.aliases))
        forward, body, cluster_aliases = place_for_gcc(self.entries, self.report)
        externs = [f"extern void {n}();" if kind == "func" else f"extern u8 {n}[];"
                   for n, kind in sorted(self.inits.externs.items()) if n not in self.defined]
        return (HEADER + "\n".join(self.types.definitions) + "\n" + "\n".join(externs) + "\n\n"
                + "\n".join(forward) + "\n\n" + "\n".join(body) + "\n"
                + alias_block(self.aliases + cluster_aliases))


# ----------------------------------------------------------------------------- placement for GCC 2.8

WORD = 4


def gcc_alignment(t) -> int:
    """The alignment GCC 2.8 for MIPS gives a variable of type `t`.

    Scalars keep their natural alignment. Arrays and structs are raised to at
    least a word, whatever their contents (the MIPS DATA_ALIGNMENT rule); that
    is what forces the clusters below.
    """
    t = t.get_canonical()
    if t.kind in (TypeKind.CONSTANTARRAY, TypeKind.INCOMPLETEARRAY):
        return max(WORD, t.element_type.get_canonical().get_align())
    if t.kind == TypeKind.RECORD:
        return max(WORD, t.get_align())
    return t.get_align()


def place_for_gcc(entries, report):
    """Definitions in address order, grouped so GCC places every byte where it was.

    GCC 2.8 emits file-scope variables in order, each at its own alignment. An
    array or struct that starts on an address that is not word aligned would
    get padding in front of it, so such runs are emitted as one packed struct
    (a cluster) that starts on a word boundary. The symbols in a cluster are
    really fields of one object; their names become #defines for the C and
    assembler aliases for the linker.

    Returns (forward declarations, definitions, cluster aliases).
    """
    runs = []
    for e in entries:
        if runs and e["addr"] % e["align"]:
            runs[-1].append(e)
        else:
            runs.append([e])
    # A cluster is a struct itself, so it too has to start on a word boundary.
    merged = []
    for run in runs:
        merged.append(run)
        while len(merged) > 1 and len(merged[-1]) > 1 and merged[-1][0]["addr"] % WORD:
            tail = merged.pop()
            merged[-1].extend(tail)

    forward, body, aliases = [], [], []
    for run in merged:
        if len(run) == 1:
            e = run[0]
            body.append(f"{e['decl']} = {e['init']};\n")
            forward.append(f"extern {e['decl']};")
            continue
        head = run[0]
        cluster = f"d2c_cluster_{head['addr']:08X}"
        members = ["    " + re.sub(rf"\b{e['name']}\b", f"m_{e['name']}", e["decl"], count=1) + ";" for e in run]
        report.note("symbols merged into a packed cluster (really fields of one object)",
                    f"{cluster}: " + ", ".join(e["name"] for e in run[1:6]) + ("..." if len(run) > 6 else ""))
        report.count("cluster members", len(run) - 1)
        forward.append(f"struct {cluster}_t\n{{\n" + "\n".join(members) + "\n} __attribute__((packed));")
        forward.append(f"extern struct {cluster}_t {cluster};")
        body.append(f"struct {cluster}_t {cluster} = {{\n    " + ",\n    ".join(e["init"] for e in run) + "\n};\n")
        for e in run:
            forward.append(f"#define {e['name']} ({cluster}.m_{e['name']})")
            if not e["name"].startswith("d2c_gap_"):
                aliases.append((e["name"], cluster, e["addr"] - head["addr"]))
    return forward, body, aliases


def alias_block(aliases) -> str:
    """Assembler definitions for names the C cannot define itself (a second name
    at one address, a field of a cluster). The PS1 linker needs them; a native
    build uses the #defines instead."""
    if not aliases:
        return ""
    lines = ["#if defined(__mips__)", "__asm__("]
    for alias, target, offset in aliases:
        expr = f"{target} + {offset:#x}" if offset else target
        lines.append(f'    "\\t.globl {alias}\\n\\t{alias} = {expr}\\n"')
    lines += [");", "#endif", ""]
    return "\n".join(lines)


def host_alias_block(aliases) -> str:
    """Second names at one address, for a host assembler. On a host every
    symbol is its own object, so only aliases at offset 0 remain."""
    if not aliases:
        return ""
    lines = ["__asm__("]
    for alias, target, offset in aliases:
        if offset:
            raise ValueError(f"alias {alias} at {target} + {offset:#x} on a host")
        lines.append(f'    "\\t.globl {alias}\\n\\t.set {alias}, {target}\\n"')
    lines += [");", ""]
    return "\n".join(lines)
