name: SLUS_010.13
sha1: d11dfdd50d412ac3fa3e2eb80fbde138da118f27
options:
  base_path: ../
  basename: SLUS_010.13
  target_path: disc/SLUS_010.13
  elf_path: build/slus_010.13.elf
  
  platform: psx
  compiler: PSYQ

  asm_path: asm
  src_path: src
  build_path: build

  ld_script_path: linker/slus_010.13.ld
  ld_dependencies: True
  ld_bss_is_noload: True

  find_file_boundaries: False
  gp_value: 0x8003EC14

  make_full_disasm_for_code: True
  o_as_suffix: True
  use_legacy_include_asm: False

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.txt
  reloc_addrs_path:
    - config/reloc_addrs.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x800, c, unk1]
      - [0xAAC, c, unk2]
      - [0x1558, c, main]
      - [0x1B58, c, decomp1]
      - [0x1F10, c, cd]
      - [0x4C48, c, decompression]
      - [0x5088, c, unk4]
      - [0x767C, c, psyq/libc2/bcopy]
      - [0x76BC, c, psyq/libc2/bzero]
      - [0x76EC, c, psyq/libc2/memcpy]
      - [0x772C, c, psyq/libc2/memset]
      - [0x775C, c, psyq/libc2/rand]
      - [0x779C, c, psyq/libc2/strcat]
      - [0x784C, c, psyq/libc2/strcmp]
      - [0x78BC, c, psyq/libc2/strcpy]
      - [0x790C, c, psyq/libc2/strlen]
      - [0x794C, c, psyq/libc2/strncmp]
      - [0x79CC, c, psyq/libc2/strncpy]
      - [0x7A3C, c, psyq/libc2/exit]
      - [0x7A4C, c, psyq/libcard/C171]
      - [0x7A5C, c, psyq/libcard/C172]
      - [0x7A6C, c, psyq/libcard/A78]
      - [0x7A7C, c, psyq/libcard/A79]
      - [0x7A8C, c, psyq/libcard/A80]
      - [0x7A9C, c, psyq/libcard/A93]
      - [0x7AAC, c, psyq/libcard/CARD]
      - [0x7AEC, c, psyq/libcard/INIT]
      - [0x7BEC, c, psyq/libapi/PAD]
      - [0x7EEC, c, psyq/libapi/A18]
      - [0x7EFC, c, psyq/libapi/A19]
      - [0x7F0C, c, psyq/libapi/A20]
      - [0x7F1C, c, psyq/libapi/A21]
      - [0x7F2C, c, psyq/libapi/L02]
      - [0x7F3C, c, psyq/libapi/L03]
      - [0x7F4C, c, psyq/libapi/PATCH]
      - [0x7FEC, c, psyq/libapi/C68]
      - [0x7FFC, c, psyq/libapi/CHCLRPAD]
      - [0x806C, c, psyq/libcard/A74]
      - [0x807C, c, psyq/libcard/A75]
      - [0x808C, c, psyq/libcard/A76]
      - [0x809C, c, psyq/libcard/PATCH]
      - [0x82BC, c, psyq/libcard/END]
      - [0x833C, c, psyq/libcard/FORMAT]
      - [0x86FC, c, psyq/libcard/A92]
      - [0x870C, c, psyq/libpress/PRESS]
      - [0x8D9C, c, psyq/libc2/PRINTF]
      - [0x8DDC, c, psyq/libc2/PRNT]
      - [0x947C, c, psyq/libc2/CTYPE]
      - [0x94EC, c, psyq/libc2/MEMCHR]
      - [0x953C, c, psyq/libc2/PUTCHAR]
      - [0x979C, c, psyq/libpress/VLC_C]
      - [0x9B1C, c, psyq/libpress/BUILD]
      - [0x9C0C, c, psyq/libgpu/SYS]
      - [0xCB3C, c, psyq/libapi/C73]
      - [0xCB4C, c, psyq/libgpu/BREAK]
      - [0xCD6C, c, psyq/libgpu/EXT]
      - [0xCE6C, c, psyq/libgpu/P17]
      - [0xCE8C, c, psyq/libgpu/P18]
      - [0xCEAC, c, psyq/libgte/GEO_00]
      - [0xCF7C, c, psyq/libgte/GEO_01]
      - [0xD01C, c, psyq/libgte/COR_02]
      - [0xD0EC, c, psyq/libgte/COR_01]
      - [0xD20C, c, psyq/libgte/COR_03]
      - [0xD3F4, c, psyq/libgte/MSC00]
      - [0xD47C, c, psyq/libgte/MSC01]
      - [0xD50C, c, psyq/libgte/MSC02]
      - [0xD7BC, c, psyq/libgte/MTX_003]
      - [0xD91C, c, psyq/libgte/MTX_004]
      - [0xDA7C, c, psyq/libgte/MTX_006]
      - [0xDBCC, c, psyq/libgte/MTX_07]
      - [0xDBFC, c, unk5]
      - [0xEB2C, c, psyq/libcd/SYS]
      - [0xF13C, c, unk6]
      - [0x10F6C, c, psyq/libetc/INTR]
      - [0x110D0, c, unk7]
      - [0x25990, data, initialized]

  - name: sdata
    type: data
    start: 0x2F414
    vram: 0x8003EC14
    subsegments:
      - [0x2F420]
  - [0x2F800]