#ifndef WMAP_LAND_EFFECT_02_H
#define WMAP_LAND_EFFECT_02_H

#include "common.h"

void wmap_land_effect_02_sequence_3_step_01();
void wmap_land_effect_02_sequence_4_step_02();
void wmap_land_effect_02_sequence_5_step_01();
void wmap_land_effect_02_sequence_5_step_02();
void wmap_land_effect_02_sequence_6_step_01();
s32 wmap_land_effect_02_run();
void wmap_land_effect_02_reset();
void wmap_land_effect_02_step_01();
void wmap_land_effect_02_wait_idle_02();
void wmap_land_effect_02_step_03();
void wmap_land_effect_02_wait_idle_04();
void wmap_land_effect_02_end();
s32 wmap_land_effect_02_run_timeline();
void wmap_land_effect_02_timeline_reset();
void wmap_land_effect_02_timeline_step_01();
void wmap_land_effect_02_timeline_wait_02();
void wmap_land_effect_02_timeline_step_03();
void wmap_land_effect_02_timeline_wait_04();
void wmap_land_effect_02_timeline_step_05();
void wmap_land_effect_02_timeline_wait_06();
void wmap_land_effect_02_timeline_step_07();
void wmap_land_effect_02_timeline_wait_08();
void wmap_land_effect_02_timeline_step_09();
void wmap_land_effect_02_timeline_wait_10();
void wmap_land_effect_02_timeline_finish();
s32 wmap_land_effect_02_run_sequence_1();
void wmap_land_effect_02_sequence_1_reset();
void wmap_land_effect_02_sequence_1_step_01();
void wmap_land_effect_02_sequence_1_step_02();
void wmap_land_effect_02_sequence_1_end();
s32 wmap_land_effect_02_run_sequence_2();
void wmap_land_effect_02_sequence_2_reset();
void wmap_land_effect_02_sequence_2_step_01();
void wmap_land_effect_02_sequence_2_step_02();
void wmap_land_effect_02_sequence_2_end();
s32 wmap_land_effect_02_run_sequence_3();
void wmap_land_effect_02_sequence_3_reset();
void wmap_land_effect_02_sequence_3_step_02();
void wmap_land_effect_02_sequence_3_step_03();
void wmap_land_effect_02_sequence_3_step_04();
void wmap_land_effect_02_sequence_3_step_05();
void wmap_land_effect_02_sequence_3_step_06();
void wmap_land_effect_02_sequence_3_end();
s32 wmap_land_effect_02_run_sequence_4();
void wmap_land_effect_02_sequence_4_reset();
void wmap_land_effect_02_sequence_4_step_01();
void wmap_land_effect_02_sequence_4_end();
s32 wmap_land_effect_02_run_sequence_5();
void wmap_land_effect_02_sequence_5_reset();
void wmap_land_effect_02_sequence_5_end();
s32 wmap_land_effect_02_run_sequence_6();
void wmap_land_effect_02_sequence_6_reset();
void wmap_land_effect_02_sequence_6_step_02();
void wmap_land_effect_02_sequence_6_step_03();
void wmap_land_effect_02_sequence_6_step_04();
void wmap_land_effect_02_sequence_6_step_05();
void wmap_land_effect_02_sequence_6_step_06();
void wmap_land_effect_02_sequence_6_end();

#endif
