#!/usr/bin/env python3
"""Generate first-pass NTSC-J splat configs and symbol maps from the US build.

The Japanese release shares most of its code with the North American one, so
the fully linked US build is used as a reference to lay out the JP binaries:

  1. Every US function (from the linked US ELFs) is masked -- immediates and
     jump targets zeroed, opcodes and registers kept -- and searched for in the
     matching JP image. A function with exactly one hit is treated as the same
     function in JP.
  2. Each JP overlay's load address is recovered from `jal` instructions that
     call matched functions, and each module's text range is extrapolated from
     the first and last matched functions using the US layout (the end is then
     trimmed back to the last `jr $ra` so trailing data is not disassembled).
  3. One splat config per module is written to config/jp/: rodata before the
     text, the whole text as a single `asm` subsegment, and data after it.
     Uniquely matched function names go to config/jp/symbols/, except US
     placeholder names (func_<address>), which splat regenerates from the JP
     address instead.

The output is a starting point for reading the JP disassembly, not a final
layout: segment boundaries are coarse and data symbols are not ported.

Requires the US build (`make` and `make overlays`) plus disc/us/ and disc/jp/.

Usage:
    python3 tools/versions/bootstrap_jp_configs.py [--force]
"""

import argparse
import collections
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "splat_ext"))
from decompress import decompress  # noqa: E402

US_MAIN = "SLUS_010.13"
JP_MAIN = "SLPS_021.70"
MAIN_VRAM = 0x80010000

JR_RA = 0x03E00008

# Auto-generated names that encode a US address.
PLACEHOLDER_NAME = re.compile(r"^(func|FUN|D|jtbl)_[0-9A-Fa-f]{8}(_[0-9A-Fa-f]+)?$")
EXE_HEADER_SIZE = 0x800

GENERATED_NOTE = (
    "# Auto-generated by tools/versions/bootstrap_jp_configs.py (first pass).\n"
    "# Coarse layout: rodata / one asm block / data. Refine by hand, then drop\n"
    "# this note.\n"
)


def elf_functions(path: Path) -> list[tuple[int, int, str]]:
    """Return (address, size, name) for every sized function symbol in an ELF."""
    data = path.read_bytes()
    shoff, = struct.unpack_from("<I", data, 0x20)
    shentsize, shnum, _ = struct.unpack_from("<HHH", data, 0x2E)
    sections = [struct.unpack_from("<10I", data, shoff + i * shentsize) for i in range(shnum)]
    functions = set()
    for sec in sections:
        if sec[1] != 2:  # SHT_SYMTAB
            continue
        strtab = sections[sec[6]]
        for k in range(sec[5] // 16):
            name_off, value, size, info, _, _ = struct.unpack_from("<IIIBBH", data, sec[4] + k * 16)
            if info & 0xF == 2 and size >= 4:  # STT_FUNC
                start = strtab[4] + name_off
                functions.add((value, size, data[start:data.index(b"\0", start)].decode()))
    return sorted(functions)


def to_words(blob: bytes) -> tuple[int, ...]:
    return struct.unpack("<%dI" % (len(blob) // 4), blob[: len(blob) // 4 * 4])


def mask_word(word: int) -> int:
    """Keep opcode and registers; drop immediates and jump targets."""
    op = word >> 26
    if op == 0:
        return word
    if op in (2, 3):
        return op << 26
    return word & 0xFFFF0000


def aligned_hits(haystack: bytes, needle: bytes) -> list[int]:
    hits = []
    pos = haystack.find(needle)
    while pos != -1:
        if pos % 4 == 0:
            hits.append(pos)
        pos = haystack.find(needle, pos + 1)
    return hits


def map_module(us_image: bytes, us_vram: int, jp_image: bytes, functions, default_vram: int) -> dict:
    """Match US functions into a JP image and derive its vram and text range."""
    us_words = to_words(us_image)
    jp_words = to_words(jp_image)
    jp_masked = struct.pack("<%dI" % len(jp_words), *map(mask_word, jp_words))

    matches = {}  # name -> (us_offset, size, jp_offset)
    for address, size, name in functions:
        offset = address - us_vram
        if offset < 0 or offset + size > len(us_image):
            continue
        needle = struct.pack("<%dI" % (size // 4), *map(mask_word, us_words[offset // 4:(offset + size) // 4]))
        hits = aligned_hits(jp_masked, needle)
        if len(hits) == 1:
            matches[name] = (offset, size, hits[0])

    # Each call from a matched function to another matched function votes for
    # the JP load address: jp_target - jp_offset_of_callee.
    by_us_offset = {us_off: jp_off for us_off, _, jp_off in matches.values()}
    votes = collections.Counter()
    for us_off, size, jp_off in matches.values():
        for i in range(size // 4):
            us_word = us_words[us_off // 4 + i]
            jp_word = jp_words[jp_off // 4 + i]
            if us_word >> 26 == 3 and jp_word >> 26 == 3:
                us_target = (((us_word & 0x3FFFFFF) << 2) | 0x80000000) - us_vram
                if us_target in by_us_offset:
                    votes[(((jp_word & 0x3FFFFFF) << 2) | 0x80000000) - by_us_offset[us_target]] += 1
    jp_vram = votes.most_common(1)[0][0] if votes else default_vram

    us_text_start = min(address for address, _, _ in functions) - us_vram
    us_text_end = max(address + size for address, size, _ in functions) - us_vram
    first = min(matches.values(), key=lambda m: m[0])
    last = max(matches.values(), key=lambda m: m[0] + m[1])
    text_start = max(0, us_text_start + (first[2] - first[0]))
    text_end = min(len(jp_image), us_text_end + (last[2] - last[0]))
    # The extrapolated end can overshoot into data when JP code near the end
    # differs in size. Trim it to just after the last `jr $ra` + delay slot,
    # but never before the end of the last matched function.
    last_matched_end = last[2] + last[1]
    for i in range(text_end // 4 - 2, last_matched_end // 4 - 3, -1):
        if jp_words[i] == JR_RA:
            text_end = max(last_matched_end, (i + 2) * 4)
            break

    # Placeholder names (func_<US address>) would mislabel the JP address, so
    # only real names are ported; splat names the rest after their JP address.
    symbols = {}
    for name, (_, size, jp_off) in sorted(matches.items(), key=lambda kv: kv[1][2]):
        if text_start <= jp_off < text_end and not PLACEHOLDER_NAME.match(name):
            symbols.setdefault(jp_vram + jp_off, (name, size))
    return {
        "vram": jp_vram,
        "text_start": text_start,
        "text_end": text_end,
        "symbols": symbols,
        "matched": len(matches),
        "total": len(functions),
    }


def write_symbols(path: Path, symbols: dict, title: str) -> None:
    lines = [
        f"// {title}",
        "// Auto-generated by tools/versions/bootstrap_jp_configs.py: US function",
        "// names whose masked instructions match exactly one place in the JP image.",
        "",
    ]
    width = max((len(name) for name, _ in symbols.values()), default=0)
    for address, (name, size) in sorted(symbols.items()):
        lines.append(f"{name:<{width}} = 0x{address:08X}; // type:func size:0x{size:X}")
    path.write_text("\n".join(lines) + "\n")


def common_options(base_path: str, basename: str, target: str, name: str, is_main: bool) -> str:
    sub = "" if is_main else f"/overlays/{name}"
    elf = f"build/jp/{JP_MAIN}.elf" if is_main else f"build/jp/overlays/{name}.elf"
    ld = f"linker/jp/{JP_MAIN}.ld" if is_main else f"linker/jp/overlays/{name}/{name}.ld"
    symbol_files = ["config/jp/symbols/shared_symbol_addrs.txt"]
    if not is_main:
        symbol_files.append(f"config/jp/symbols/{name}_symbol_addrs.txt")
    return (
        "options:\n"
        f"  base_path: {base_path}\n"
        f"  basename: {basename}\n"
        "  platform: psx\n"
        "  compiler: PSYQ\n"
        "  # include/include_asm.h and the .inc files are project-owned.\n"
        "  generate_asm_macros_files: False\n"
        f"  target_path: {target}\n"
        "  extensions_path: tools/splat_ext\n"
        "  asset_path: assets/jp\n"
        f"  elf_path: {elf}\n"
        "\n"
        f"  asm_path: asm/jp{sub}\n"
        f"  src_path: src{sub}\n"
        f"  build_path: build/jp{sub}\n"
        "\n"
        f"  ld_script_path: {ld}\n"
        "  ld_dependencies: True\n"
        f"  undefined_funcs_auto_path: linker/jp{sub}/undefined_funcs_auto.txt\n"
        f"  undefined_syms_auto_path: linker/jp{sub}/undefined_syms_auto.txt\n"
        "\n"
        "  symbol_addrs_path:\n"
        + "".join(f"    - {f}\n" for f in symbol_files)
        + "\n"
        "  find_file_boundaries: False\n"
        "  make_full_disasm_for_code: True\n"
        "  use_legacy_include_asm: False\n"
        "  o_as_suffix: True\n"
        "  subalign: 2\n"
        "\n"
        '  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]\n'
        "\n"
        "  # ASCII, not SHIFT-JIS: splat writes decoded strings into the .s files\n"
        "  # as UTF-8, which reassembles to different (longer) bytes. Japanese\n"
        "  # text stays as raw data so the disassembly round-trips exactly.\n"
        "  string_encoding: ASCII\n"
        "  data_string_encoding: ASCII\n"
    )


def subsegments(name: str, file_offset: int, text_start: int, text_end: int, image_size: int) -> str:
    """rodata / asm / data subsegments; offsets are image offsets + file_offset."""
    rows = []
    if text_start > 0:
        rows.append(f"      - [0x{file_offset:X}, rodata, {name}_rodata]")
    rows.append(f"      - [0x{file_offset + text_start:X}, asm, {name}_text]")
    if text_end < image_size:
        rows.append(f"      - [0x{file_offset + text_end:X}, data, {name}_data]")
    return "\n".join(rows) + "\n"


def sha1(path: Path) -> str:
    import hashlib
    return hashlib.sha1(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--force", action="store_true", help="overwrite existing config/jp yamls and symbol files")
    args = parser.parse_args()

    config_dir = ROOT / "config" / "jp"
    symbol_dir = config_dir / "symbols"
    overlay_dir = config_dir / "overlays"
    main_yaml = config_dir / f"{JP_MAIN}.yaml"
    if main_yaml.exists() and not args.force:
        print(f"{main_yaml} already exists; pass --force to regenerate", file=sys.stderr)
        return 1
    symbol_dir.mkdir(parents=True, exist_ok=True)
    overlay_dir.mkdir(parents=True, exist_ok=True)

    # ── Main executable ──
    us_exe = (ROOT / "disc/us" / US_MAIN).read_bytes()[EXE_HEADER_SIZE:]
    jp_path = ROOT / "disc/jp" / JP_MAIN
    jp_exe = jp_path.read_bytes()[EXE_HEADER_SIZE:]
    result = map_module(us_exe, MAIN_VRAM, jp_exe, elf_functions(ROOT / f"build/us/{US_MAIN}.elf"), MAIN_VRAM)
    gp = find_gp(jp_exe)
    write_symbols(symbol_dir / "shared_symbol_addrs.txt", result["symbols"], f"{JP_MAIN} main executable")
    main_yaml.write_text(
        GENERATED_NOTE
        + f"name: {JP_MAIN}\nsha1: {sha1(jp_path)}\n"
        + common_options("../../", JP_MAIN, f"disc/jp/{JP_MAIN}", "main", True)
        + f"  gp_value: 0x{gp:08X}\n"
        + "  ld_bss_is_noload: True\n"
        + "\nsegments:\n  - name: header\n    type: header\n    start: 0x0\n\n"
        + f"  - name: main\n    type: code\n    start: 0x{EXE_HEADER_SIZE:X}\n    vram: 0x{MAIN_VRAM:08X}\n"
        + "    align: 4\n    subsegments:\n"
        + subsegments("main", EXE_HEADER_SIZE, result["text_start"], result["text_end"], len(jp_exe))
        + f"  - [0x{EXE_HEADER_SIZE + len(jp_exe):X}]\n"
    )
    print(f"main     vram=0x{MAIN_VRAM:08X} gp=0x{gp:08X} text=0x{result['text_start']:X}..0x{result['text_end']:X} "
          f"names={len(result['symbols'])} ({result['matched']}/{result['total']} matched)")

    # ── Overlays ──
    for us_yaml in sorted((ROOT / "config/us/overlays").glob("*.BIN.yaml")):
        basename = us_yaml.name[: -len(".yaml")]
        name = basename[: -len(".BIN")].lower()
        us_vram = int(re.search(r"vram:\s*(0x[0-9A-Fa-f]+)", us_yaml.read_text()).group(1), 16)
        us_image = bytes(decompress((ROOT / "disc/us/BIN" / basename).read_bytes()[1:]))
        jp_bin = ROOT / "disc/jp/BIN" / basename
        jp_image = bytes(decompress(jp_bin.read_bytes()[1:]))
        result = map_module(us_image, us_vram, jp_image,
                            elf_functions(ROOT / f"build/us/overlays/{name}/{name}.elf"), us_vram)
        write_symbols(symbol_dir / f"{name}_symbol_addrs.txt", result["symbols"], f"{basename} overlay")
        # Overlay subsegment offsets are image offsets + 1 (the format byte).
        (overlay_dir / f"{basename}.yaml").write_text(
            GENERATED_NOTE
            + f"name: {basename}\nsha1: {sha1(jp_bin)}\n"
            + common_options("../../../", basename, f"disc/jp/BIN/{basename}", name, False)
            + f"\nsegments:\n  - name: {name}\n    type: decompress_overlay\n    start: 0x1\n"
            + f"    vram: 0x{result['vram']:08X}\n    align: 4\n    subsegments:\n"
            + subsegments(name, 1, result["text_start"], result["text_end"], len(jp_image))
            + f"  - [0x{1 + len(jp_image):X}]\n"
        )
        print(f"{name:<8} vram=0x{result['vram']:08X} text=0x{result['text_start']:X}..0x{result['text_end']:X} "
              f"names={len(result['symbols'])} ({result['matched']}/{result['total']} matched)")
    return 0


def find_gp(exe: bytes) -> int:
    """Return the value loaded into $gp by a `lui gp` / `addiu gp, gp` pair."""
    words = to_words(exe)
    for i, word in enumerate(words):
        if word >> 16 != 0x3C1C:  # lui $gp
            continue
        for follow in words[i + 1:i + 6]:
            if follow >> 16 in (0x279C, 0x379C):  # addiu/ori $gp, $gp
                imm = follow & 0xFFFF
                if follow >> 16 == 0x279C and imm & 0x8000:
                    imm -= 0x10000
                return (((word & 0xFFFF) << 16) + imm) & 0xFFFFFFFF
    raise RuntimeError("could not find $gp initialisation")


if __name__ == "__main__":
    sys.exit(main())
