#ifndef WMAP_SPECIAL_EFFECT_34_H
#define WMAP_SPECIAL_EFFECT_34_H

#include "common.h"

void wmap_special_effect_34_sequence_1_step_02();
void wmap_special_effect_34_sequence_1_step_04();
void wmap_special_effect_34_sequence_1_step_06();
void wmap_special_effect_34_sequence_2_step_01();
void wmap_special_effect_34_sequence_2_step_03();
void wmap_special_effect_34_sequence_2_step_05();
void wmap_special_effect_34_sequence_2_step_07();
void wmap_special_effect_34_sequence_3_step_02();
s32 wmap_special_effect_34_run();
void wmap_special_effect_34_step_00();
void wmap_special_effect_34_step_01();
void wmap_special_effect_34_step_02();
void wmap_special_effect_34_step_03();
void wmap_special_effect_34_step_04();
void wmap_special_effect_34_step_05();
void wmap_special_effect_34_step_06();
void wmap_special_effect_34_step_07();
s32 wmap_special_effect_34_run_timeline();
void wmap_special_effect_34_timeline_step_00();
void wmap_special_effect_34_timeline_step_01();
void wmap_special_effect_34_timeline_step_02();
void wmap_special_effect_34_timeline_step_03();
void wmap_special_effect_34_timeline_step_04();
void wmap_special_effect_34_timeline_step_05();
void wmap_special_effect_34_timeline_step_06();
void wmap_special_effect_34_timeline_step_07();
void wmap_special_effect_34_timeline_step_08();
void wmap_special_effect_34_timeline_step_09();
void wmap_special_effect_34_timeline_step_10();
void wmap_special_effect_34_timeline_step_11();
void wmap_special_effect_34_timeline_step_12();
void wmap_special_effect_34_timeline_finish();
s32 wmap_special_effect_34_run_sequence_1();
void wmap_special_effect_34_sequence_1_reset();
void wmap_special_effect_34_sequence_1_step_01();
void wmap_special_effect_34_sequence_1_step_03();
void wmap_special_effect_34_sequence_1_step_05();
void wmap_special_effect_34_sequence_1_step_07();
s32 wmap_special_effect_34_run_sequence_2();
void wmap_special_effect_34_sequence_2_reset();
void wmap_special_effect_34_sequence_2_step_02();
void wmap_special_effect_34_sequence_2_step_04();
void wmap_special_effect_34_sequence_2_step_06();
void wmap_special_effect_34_sequence_2_step_08();
void wmap_special_effect_34_sequence_2_step_09();
s32 wmap_special_effect_34_run_sequence_3();
void wmap_special_effect_34_sequence_3_reset();
void wmap_special_effect_34_sequence_3_step_01();
void wmap_special_effect_34_sequence_3_step_03();
void wmap_special_effect_34_sequence_3_step_04();
void wmap_special_effect_34_sequence_3_end();
s32 wmap_special_effect_34_run_sequence_4();
void wmap_special_effect_34_sequence_4_reset();
void wmap_special_effect_34_sequence_4_step_01();
void wmap_special_effect_34_sequence_4_step_02();
void wmap_special_effect_34_sequence_4_step_03();
void wmap_special_effect_34_sequence_4_step_04();
void wmap_special_effect_34_sequence_4_end();
void func_800C0C5C();

#endif
