#!/usr/bin/env python3
"""Generate the gitignored initializer fragments for GNAME's .data tables from
the original (copyrighted) disc image.

The GNAME overlay is stored compressed on disc. splat's decompress_overlay step
inflates it and places the decompressed image at the segment rom_start so
subsegment offsets index correctly. We reproduce that here, then slice the
.data region into one fragment per named symbol (from gname_symbol_addrs.txt).

The committed gname_data.c holds the schema (the array declarations, one per
symbol) and #includes these fragments. The fragments hold ONLY data values and
are gitignored, keeping copyrighted content out of source control while letting
the linker build the section by compiling C - not by including a raw blob.

Usage:
    python tools/gen_gname_data.py            # write the fragments
    python tools/gen_gname_data.py --check    # verify against extracted asset
    python tools/gen_gname_data.py --scaffold # print suggested C declarations
"""

import argparse
import importlib.util
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# --- Overlay/segment geometry (from config/overlays/GNAME.BIN.yaml) ----------
DISC_PATH = REPO_ROOT / "disc" / "BIN" / "GNAME.BIN"
SEG_ROM_START = 0x1       # segment 'start' in the yaml
SEG_ROM_END = 0xF8D9      # trailing position marker in the yaml
DATA_ROM_START = 0x2C99   # .data subsegment offset
DATA_ROM_END = 0xF7B1     # following subsegment (.bss) offset

# VRAM of the .data region start (rom offset DATA_ROM_START maps here because
# the decompressed image is placed at SEG_ROM_START == rom offset 0x1).
DATA_VRAM_START = 0x80142C98
DATA_VRAM_END = 0x8014F7B0  # first .bss symbol (g_custom_name_buf)

SYMBOL_FILE = REPO_ROOT / "config" / "symbols" / "gname_symbol_addrs.txt"
GEN_DIR = REPO_ROOT / "src" / "overlays" / "gname" / "gen"
REFERENCE_ASSET = REPO_ROOT / "assets" / "gname_data.databin.bin"

BYTES_PER_LINE = 12
_SYM_RE = re.compile(r"^\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;")


def _load_decompress():
    ext = REPO_ROOT / "tools" / "splat_ext" / "decompress.py"
    spec = importlib.util.spec_from_file_location("decompress", ext)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.decompress


def extract_data_bytes() -> bytes:
    """Reproduce splat's decompressed image and slice the .data range."""
    decompress = _load_decompress()
    rom = DISC_PATH.read_bytes()
    decompressed = decompress(rom[SEG_ROM_START:SEG_ROM_END])

    image = bytearray(SEG_ROM_START + len(decompressed))
    image[SEG_ROM_START:] = decompressed

    data = bytes(image[DATA_ROM_START:DATA_ROM_END])
    expected = DATA_VRAM_END - DATA_VRAM_START
    if len(data) != expected:
        sys.exit(f"ERROR: sliced {len(data)} bytes, expected {expected}")
    return data


def region_symbols():
    """Return [(name, vram)] for every symbol in the .data region, sorted."""
    syms = []
    for line in SYMBOL_FILE.read_text().splitlines():
        m = _SYM_RE.match(line)
        if not m:
            continue
        addr = int(m.group(2), 16)
        if DATA_VRAM_START <= addr < DATA_VRAM_END:
            syms.append((m.group(1), addr))
    syms.sort(key=lambda t: t[1])
    if not syms or syms[0][1] != DATA_VRAM_START:
        sys.exit(f"ERROR: region does not start at 0x{DATA_VRAM_START:X}")
    return syms


def slices(data: bytes):
    """Yield (name, vram, size, bytes) partitioning the region by symbol."""
    syms = region_symbols()
    bounds = [addr for _, addr in syms] + [DATA_VRAM_END]
    for i, (name, addr) in enumerate(syms):
        start = addr - DATA_VRAM_START
        end = bounds[i + 1] - DATA_VRAM_START
        yield name, addr, end - start, data[start:end]


def render_fragment(name: str, data: bytes) -> str:
    lines = [f"/* GENERATED by tools/gen_gname_data.py for {name} - do not edit or commit. */"]
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        lines.append("    " + "".join(f"0x{b:02X}, " for b in chunk).rstrip())
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify extracted bytes match the extracted asset")
    parser.add_argument("--scaffold", action="store_true",
                        help="print suggested C declarations and exit")
    args = parser.parse_args()

    data = extract_data_bytes()

    if args.check:
        if not REFERENCE_ASSET.exists():
            sys.exit(f"ERROR: reference asset not found: {REFERENCE_ASSET}")
        ref = REFERENCE_ASSET.read_bytes()
        if data != ref:
            sys.exit(f"MISMATCH: extracted {len(data)} vs reference {len(ref)}")
        total = 0
        for name, addr, size, _ in slices(data):
            print(f"  0x{addr:08X}  {size:6d}  {name}")
            total += size
        print(f"OK: {total} bytes across {len(list(slices(data)))} tables "
              f"match {REFERENCE_ASSET.name}")
        return

    if args.scaffold:
        for name, addr, size, _ in slices(data):
            print(f'unsigned char {name}[] = {{  /* 0x{addr:08X}, {size} bytes */')
            print(f'#include "gen/{name}.inc"')
            print("};")
        return

    GEN_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for name, _, _, chunk in slices(data):
        (GEN_DIR / f"{name}.inc").write_text(render_fragment(name, chunk), newline="\n")
        count += 1
    print(f"Wrote {count} fragments to {GEN_DIR.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
